// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_Data.Data;

#nullable disable

namespace Project_Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20241127042214_update_v21")]
    partial class update_v21
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project_Model.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            name = "Trousers"
                        },
                        new
                        {
                            Id = 2,
                            name = "Shirt"
                        },
                        new
                        {
                            Id = 3,
                            name = "Accessory"
                        },
                        new
                        {
                            Id = 4,
                            name = "Jacket"
                        });
                });

            modelBuilder.Entity("Project_Model.Entities.ConfirmEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfirmCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ConfirmEmails");
                });

            modelBuilder.Entity("Project_Model.Entities.Materials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cotton"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Silk"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Leather"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Demin"
                        });
                });

            modelBuilder.Entity("Project_Model.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TotalPrice")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Project_Model.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("img_product")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Project_Model.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Project_Model.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CateId")
                        .HasColumnType("int");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<int>("MateId")
                        .HasColumnType("int");

                    b.Property<int>("countOfProduct")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("img_product")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CateId");

                    b.HasIndex("MateId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CateId = 2,
                            IsActive = 1,
                            MateId = 1,
                            countOfProduct = 16,
                            description = "OverSize",
                            img_product = "https://product.hstatic.net/1000306633/product/hadesss5271_2b14558975cf4a63ad9846c38d389ae0.jpg",
                            name = "Pink Shirt",
                            price = 10f
                        },
                        new
                        {
                            Id = 2,
                            CateId = 2,
                            IsActive = 1,
                            MateId = 1,
                            countOfProduct = 15,
                            description = "Unisex",
                            img_product = "https://product.hstatic.net/1000306633/product/hades_15sp6459_f56b1b52184547be948ca85de8c6945b.jpg",
                            name = "Yellow Shirt",
                            price = 15f
                        },
                        new
                        {
                            Id = 3,
                            CateId = 2,
                            IsActive = 1,
                            MateId = 1,
                            countOfProduct = 19,
                            description = "Unisex",
                            img_product = "https://product.hstatic.net/1000306633/product/untitled_capture1415_65c895bbd43f4d4592ad13fbdd6c2dec_grande.jpg",
                            name = "Blue Shirt",
                            price = 20f
                        },
                        new
                        {
                            Id = 4,
                            CateId = 2,
                            IsActive = 1,
                            MateId = 1,
                            countOfProduct = 14,
                            description = "Unisex",
                            img_product = "https://product.hstatic.net/1000306633/product/untitled_capture0379_382dbd36ba5c47998070f2c5dfdc28d7_grande.jpeg",
                            name = "White Shirt",
                            price = 20f
                        },
                        new
                        {
                            Id = 5,
                            CateId = 1,
                            IsActive = 1,
                            MateId = 4,
                            countOfProduct = 20,
                            description = "New Jean",
                            img_product = "https://product.hstatic.net/1000306633/product/hades_15sp2861_68d195870f744d1f97b92ece3161fd07.jpg",
                            name = "SPLINTERED PANTS",
                            price = 50f
                        },
                        new
                        {
                            Id = 6,
                            CateId = 1,
                            IsActive = 1,
                            MateId = 4,
                            countOfProduct = 30,
                            description = "Black Jean Collection 2024",
                            img_product = "https://product.hstatic.net/1000306633/product/dsc06440_0b8adfc8e5d44cb5b5be6749317ac6fc.jpg",
                            name = "VINDHEIRM PANTS",
                            price = 50f
                        },
                        new
                        {
                            Id = 7,
                            CateId = 1,
                            IsActive = 1,
                            MateId = 4,
                            countOfProduct = 40,
                            description = "Grey Jean New Collection 2024",
                            img_product = "https://product.hstatic.net/1000306633/product/group_1_63b8c7543828429d8da58ee55c49ff3b.jpg",
                            name = "Gray Jean",
                            price = 50f
                        },
                        new
                        {
                            Id = 8,
                            CateId = 1,
                            IsActive = 1,
                            MateId = 4,
                            countOfProduct = 50,
                            description = "Wide leg pants, straight form, heel length",
                            img_product = "https://product.hstatic.net/1000306633/product/untitled_capture1110_82b081c12676489484ab516558460333.jpg",
                            name = "Casual Pants",
                            price = 50f
                        },
                        new
                        {
                            Id = 9,
                            CateId = 1,
                            IsActive = 1,
                            MateId = 4,
                            countOfProduct = 70,
                            description = "Wash treatment creates a unique effect. Pants are treated with vertical seaming.",
                            img_product = "https://product.hstatic.net/1000306633/product/hd_t10.2600_e87fc3429cd54b2589ecc720a60567c9.jpg",
                            name = "Tectonic Rift Jeans",
                            price = 50f
                        },
                        new
                        {
                            Id = 10,
                            CateId = 3,
                            IsActive = 1,
                            MateId = 1,
                            countOfProduct = 100,
                            description = "Baseball cap with typo embroidery on front and left side, soft lining inside. Tear treatment details. Hat has metal button to adjust width at back",
                            img_product = "https://product.hstatic.net/1000306633/product/hades5355_f8801511953643219ab90b841c271485.jpg",
                            name = "PROFILE ELLIPSE CAP",
                            price = 10f
                        },
                        new
                        {
                            Id = 11,
                            CateId = 2,
                            IsActive = 1,
                            MateId = 1,
                            countOfProduct = 70,
                            description = "New basic form. Silk screen printing on front and back of shirt",
                            img_product = "https://product.hstatic.net/1000306633/product/dsc02378_20cb26b74d314381a455691e0f57c305.jpg",
                            name = "SLEEPLESS SAIGON TEE",
                            price = 50f
                        },
                        new
                        {
                            Id = 12,
                            CateId = 2,
                            IsActive = 1,
                            MateId = 1,
                            countOfProduct = 80,
                            description = "New basic form. Silk screen printing on front and back of shirt",
                            img_product = "https://product.hstatic.net/1000306633/product/dsc09856_1d3a8091abae4a6ab6d4e9256df2b4e9.jpg",
                            name = "CERISE BOW TEE",
                            price = 50f
                        },
                        new
                        {
                            Id = 13,
                            CateId = 2,
                            IsActive = 1,
                            MateId = 1,
                            countOfProduct = 120,
                            description = "Tank Top form. Silk screen printing on front and back of shirt",
                            img_product = "https://product.hstatic.net/1000306633/product/dsc09825_5bfd1c357e244cb09f9e764802226c89.jpg",
                            name = "SONOROUS TANK TOP",
                            price = 50f
                        },
                        new
                        {
                            Id = 14,
                            CateId = 2,
                            IsActive = 1,
                            MateId = 1,
                            countOfProduct = 130,
                            description = "New basic form. Silk screen printing on front and back of shirt",
                            img_product = "https://product.hstatic.net/1000306633/product/truoc_a5458ac1af084d18bcb742c0858a9cec.jpg",
                            name = "FLEURS RED TEE",
                            price = 50f
                        },
                        new
                        {
                            Id = 15,
                            CateId = 2,
                            IsActive = 1,
                            MateId = 1,
                            countOfProduct = 140,
                            description = "New basic form. Silk screen printing on front and back of shirt",
                            img_product = "https://product.hstatic.net/1000306633/product/dsc02391_5cd7373e7fee45ec832b2aac535943e2.jpg",
                            name = "CERISE CRAVAT TEE",
                            price = 50f
                        },
                        new
                        {
                            Id = 16,
                            CateId = 2,
                            IsActive = 1,
                            MateId = 1,
                            countOfProduct = 90,
                            description = "Unisex long-sleeved shirt. Stylized H symbol embroidered on front pocket",
                            img_product = "https://product.hstatic.net/1000306633/product/hadest62190_1f74f7e3338d464a91a8d6ede97fb24c.jpg",
                            name = "STRIPED SHIRT 24",
                            price = 50f
                        },
                        new
                        {
                            Id = 17,
                            CateId = 2,
                            IsActive = 1,
                            MateId = 1,
                            countOfProduct = 120,
                            description = "2 Bling charms are attached to the front of the shirt",
                            img_product = "https://product.hstatic.net/1000306633/product/hades7763_c37388c75a0e4878bfa580e9992199d3.jpg",
                            name = "WHITE ASTRAL SHIRT",
                            price = 50f
                        },
                        new
                        {
                            Id = 18,
                            CateId = 2,
                            IsActive = 1,
                            MateId = 2,
                            countOfProduct = 180,
                            description = "Full body zip. Shirt collar. The shirt body is processed with layering technique on the shirt combined with zip. The lettering on the front of the shirt is silk-screen printed.",
                            img_product = "https://product.hstatic.net/1000306633/product/anhtruoc_b151879109654a85ba10e95cf14ac9e5.jpg",
                            name = "TRACER SLEEVES BOXY SHIRT",
                            price = 50f
                        },
                        new
                        {
                            Id = 19,
                            CateId = 4,
                            IsActive = 1,
                            MateId = 3,
                            countOfProduct = 70,
                            description = "Full zip leather jacket. Shirt collar. Front and back details create contrasting color blocks",
                            img_product = "https://product.hstatic.net/1000306633/product/dsc04281_970f8f362b644db1827885d9995c8368.jpg",
                            name = "AQUILINE LEATHER JACKET",
                            price = 50f
                        },
                        new
                        {
                            Id = 20,
                            CateId = 4,
                            IsActive = 1,
                            MateId = 3,
                            countOfProduct = 10,
                            description = "Full zip leather jacket. Collar with metal snap button Shop logo",
                            img_product = "https://product.hstatic.net/1000306633/product/hades_15sp9026_ec8d570de1384e218bb5295c0f08df67.jpg",
                            name = "BROWN WAX BIKER JACKET",
                            price = 50f
                        },
                        new
                        {
                            Id = 21,
                            CateId = 4,
                            IsActive = 1,
                            MateId = 3,
                            countOfProduct = 140,
                            description = "Full zip leather jacket. Typo graphic on shirt uses a combination of 3 techniques: regular embroidery, embossed embroidery and leather patchwork",
                            img_product = "https://product.hstatic.net/1000306633/product/untitled_capture1066_f59c6bb3b46d4b9e899b07424f909096.jpg",
                            name = "911 LEATHER JACKET",
                            price = 50f
                        },
                        new
                        {
                            Id = 22,
                            CateId = 3,
                            IsActive = 1,
                            MateId = 2,
                            countOfProduct = 150,
                            description = "Size: 57 x 57 cm",
                            img_product = "https://product.hstatic.net/1000306633/product/khan2_49fd68354ca04168bf8bd280c8ff4b17.jpg",
                            name = "GOODIES TURBAN",
                            price = 20f
                        },
                        new
                        {
                            Id = 23,
                            CateId = 3,
                            IsActive = 1,
                            MateId = 2,
                            countOfProduct = 170,
                            description = "Size: 57 x 57 cm",
                            img_product = "https://product.hstatic.net/1000306633/product/khan_1c1016cc7f5c450783adafa38d181647.jpg",
                            name = "SIGNATURE TURBAN",
                            price = 20f
                        },
                        new
                        {
                            Id = 24,
                            CateId = 1,
                            IsActive = 1,
                            MateId = 4,
                            countOfProduct = 210,
                            description = "Regular fit. Elastic waistband with drawstring. Flared details and vertical slits on front and back of pants. Sshop logo embroidered on front of pants",
                            img_product = "https://product.hstatic.net/1000306633/product/hades0097_12db902901f74837a31a277067358285.jpg",
                            name = "SYMMETRY PANTS",
                            price = 30f
                        },
                        new
                        {
                            Id = 25,
                            CateId = 1,
                            IsActive = 1,
                            MateId = 4,
                            countOfProduct = 140,
                            description = "Unisex cropped jeans, knee length, wide leg. Wash treatment creates a unique effect. Stand out with fabric patchwork details and tear treatment on the front. 2 front pockets and 2 back pockets. Lettering embroidered on the back pocket",
                            img_product = "https://product.hstatic.net/1000306633/product/hd_t21120_b4ee1be19b714797be823f8d728b4b94.jpg",
                            name = "WASH JEANS SHORT",
                            price = 40f
                        },
                        new
                        {
                            Id = 26,
                            CateId = 1,
                            IsActive = 1,
                            MateId = 4,
                            countOfProduct = 10,
                            description = "Elastic waistband pants with drawstring. Details on pants use silk screen printing technique. Cool fabric, form-fitting",
                            img_product = "https://product.hstatic.net/1000306633/product/hd_t21411_5587cc83065e48e0a02206508b25518c.jpg",
                            name = "SIGNATURE TURBAN",
                            price = 400f
                        },
                        new
                        {
                            Id = 27,
                            CateId = 1,
                            IsActive = 1,
                            MateId = 4,
                            countOfProduct = 120,
                            description = "Love Pink",
                            img_product = "https://product.hstatic.net/1000306633/product/multi_hong_pant_e33a46466fe64c4982ae4fc543f0b839.jpg",
                            name = "MULTI TROUSER PANTS",
                            price = 320f
                        },
                        new
                        {
                            Id = 28,
                            CateId = 1,
                            IsActive = 1,
                            MateId = 4,
                            countOfProduct = 170,
                            description = "Elastic waistband skirt with drawstring. Using the technique of assembling the front and back of the skirt, 2 front slit pockets and 2 back slit pockets with 2 box pockets. Embroidered lettering. Drawstring at the hem of the skirt for decoration",
                            img_product = "https://product.hstatic.net/1000306633/product/z4908503993219_2a3ba233739e6c352441ded60c16ae49_3e0378a895c9427595ff337f4cb745f8.jpg",
                            name = "NEUTRAL CARGO PARACHUTE SKIRT",
                            price = 240f
                        },
                        new
                        {
                            Id = 29,
                            CateId = 1,
                            IsActive = 1,
                            MateId = 4,
                            countOfProduct = 110,
                            description = "Wide leg, low waistband, heel length trousers. Metal Hades logo back button. Sturdy zip pocket details along leg. Decorative belt and metal details",
                            img_product = "https://product.hstatic.net/1000306633/product/hd_t21557_90cf650878c64cebad12de2b26654670.jpg",
                            name = "KNIGHT HUSH PANTS",
                            price = 210f
                        },
                        new
                        {
                            Id = 30,
                            CateId = 4,
                            IsActive = 1,
                            MateId = 3,
                            countOfProduct = 120,
                            description = "Full zip jacket. 2 front pockets. Cuffs and body. Front and back details combined with reflective lines create a striking effect. Silk screen printing technique on the front and back of the shirt",
                            img_product = "https://product.hstatic.net/1000306633/product/dsc04327_30d4e89a5ca74b098dda2da3532692a3.jpg",
                            name = "RACER VAIN JACKET",
                            price = 250f
                        },
                        new
                        {
                            Id = 31,
                            CateId = 4,
                            IsActive = 1,
                            MateId = 3,
                            countOfProduct = 160,
                            description = "Jacket with zip fastening along the body. Drawstrings on the sleeves and body. Using fabric seaming technique. Lettering details on the front of the shirt are embroidered. There are 2 large front pockets and other metal buttons.",
                            img_product = "https://product.hstatic.net/1000306633/product/hades_16.06.23.7405_88fd05cb27fc418783a823b6aea4e26b.jpg",
                            name = "MAJOR PIECES JACKET",
                            price = 100f
                        },
                        new
                        {
                            Id = 32,
                            CateId = 4,
                            IsActive = 1,
                            MateId = 3,
                            countOfProduct = 210,
                            description = "The pocket details are designed to overlap each other. The body and sleeves are trimmed. The lettering details use embossed embroidery techniques. The shirt uses fabric joining techniques. The zipper runs along the body.",
                            img_product = "https://product.hstatic.net/1000306633/product/hades_16.06.23.8442_4ce30c9157f7405ba8c92e2defb72917.jpg",
                            name = "LOOMING ZIP JACKET",
                            price = 70f
                        },
                        new
                        {
                            Id = 33,
                            CateId = 4,
                            IsActive = 1,
                            MateId = 3,
                            countOfProduct = 110,
                            description = "Design of 2 large front pockets. Body and sleeve trim. Letters on the shirt use embossed embroidery technique. Stainless steel nameplate attached to the collar. Zipper along the body",
                            img_product = "https://product.hstatic.net/1000306633/product/dsc06847_copy_2b565216a330490aa55ac91798b0506d.jpg",
                            name = "FEEL ALIVE JACKET",
                            price = 50f
                        },
                        new
                        {
                            Id = 34,
                            CateId = 4,
                            IsActive = 1,
                            MateId = 3,
                            countOfProduct = 310,
                            description = "Specially embroidered streetwear motifs. Thin lining on the inside. Ribbed collar, cuffs and hem. Snap buttons along the length of the shirt",
                            img_product = "https://product.hstatic.net/1000306633/product/2510_1_140d7a21069e4c7a88ddc3f1b04c6a18.jpg",
                            name = "GLORY ROAD BROWN VARSITY JACKET",
                            price = 200f
                        },
                        new
                        {
                            Id = 35,
                            CateId = 3,
                            IsActive = 1,
                            MateId = 3,
                            countOfProduct = 20,
                            description = "Size: large flower 20x20cm, small flower 12x12cm, flower branch 9x3cm, flower leaf 5x2.5cm",
                            img_product = "https://product.hstatic.net/1000306633/product/hades_15sp7245_17a8c69e483545de8a53b487873bd8a1.jpg",
                            name = "BLOOMING CROSS BAG",
                            price = 220f
                        },
                        new
                        {
                            Id = 36,
                            CateId = 3,
                            IsActive = 1,
                            MateId = 3,
                            countOfProduct = 110,
                            description = "Sturdy metal zipper2 zipped shoulder straps can be carried in 2 ways. Spacious storage compartment. Decorative rivet details. Waterproof. Dimensions: height 35cm x width 26cm x width 12cm",
                            img_product = "https://product.hstatic.net/1000306633/product/hades_15sp9301_0d434600402f4005aa695b095fbf8eb4.jpg",
                            name = "BACKPACK LEATHER 24",
                            price = 250f
                        },
                        new
                        {
                            Id = 37,
                            CateId = 3,
                            IsActive = 1,
                            MateId = 3,
                            countOfProduct = 10,
                            description = "Baseball cap with typo embroidery on front and right side, soft lining inside. Front and back details combined with embossed lines create contrasting color blocks. Hat has metal nameplate to increase or decrease width at the back",
                            img_product = "https://product.hstatic.net/1000306633/product/dsc04515_4dab82fb55504989b747f7afbe3dcbf6.jpg",
                            name = "TAILWIND CAP",
                            price = 25f
                        },
                        new
                        {
                            Id = 38,
                            CateId = 3,
                            IsActive = 1,
                            MateId = 3,
                            countOfProduct = 60,
                            description = "Unisex design tote bag. Wolf mascot charm. Shop logo plastic tag. Size: Width 36 x Length 32 (cm)",
                            img_product = "https://product.hstatic.net/1000306633/product/hades5649_7424dd8ada6944e2a9f8567dc5f9288c.jpg",
                            name = "MASCOT BLACK TOTE BAG",
                            price = 50f
                        },
                        new
                        {
                            Id = 39,
                            CateId = 3,
                            IsActive = 1,
                            MateId = 3,
                            countOfProduct = 50,
                            description = "Metal Shop Logo. Waterproof. Many spacious storage compartments. Plastic lock details and metal clasps create highlights.",
                            img_product = "https://product.hstatic.net/1000306633/product/dsc02422_94b87132902c47f9a362f4c3ce45ad0d.jpg",
                            name = "NEOPRENE UTILITY BACKPACK",
                            price = 20f
                        },
                        new
                        {
                            Id = 40,
                            CateId = 3,
                            IsActive = 1,
                            MateId = 3,
                            countOfProduct = 90,
                            description = "Metal Shop Logo. Sturdy metal zipper and button details. Waterproof. Many compartments and spacious pockets. Dimensions: 42 x 33 x 17cm.",
                            img_product = "https://product.hstatic.net/1000306633/product/z5423912627963_73128c420eccecfc5fe2e86113e59334_273e27b606004b19aceba5f77849be77.jpg",
                            name = "MOTIVATION GRUNGE BACKPACK",
                            price = 20f
                        });
                });

            modelBuilder.Entity("Project_Model.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Project_Model.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleCode = "Admin",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleCode = "User",
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("Project_Model.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Project_Model.Entities.ConfirmEmail", b =>
                {
                    b.HasOne("Project_Model.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project_Model.Entities.Order", b =>
                {
                    b.HasOne("Project_Model.Entities.User", "User")
                        .WithMany("Order")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project_Model.Entities.OrderDetail", b =>
                {
                    b.HasOne("Project_Model.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_Model.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Project_Model.Entities.Permission", b =>
                {
                    b.HasOne("Project_Model.Entities.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_Model.Entities.User", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project_Model.Entities.Product", b =>
                {
                    b.HasOne("Project_Model.Entities.Category", "Cate")
                        .WithMany("products")
                        .HasForeignKey("CateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_Model.Entities.Materials", "Mate")
                        .WithMany("products")
                        .HasForeignKey("MateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cate");

                    b.Navigation("Mate");
                });

            modelBuilder.Entity("Project_Model.Entities.RefreshToken", b =>
                {
                    b.HasOne("Project_Model.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project_Model.Entities.Category", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Project_Model.Entities.Materials", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Project_Model.Entities.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Project_Model.Entities.User", b =>
                {
                    b.Navigation("Order");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
